#!/usr/bin/env bash
set -Eeuo pipefail

# EH-10-05 is intentionally a synthetic, deployment-neutral acceptance seam.
# The production image is exercised as web and worker roles; the build stage
# supplies the development-only Prisma/Vitest tooling for the PostgreSQL
# fixture suite. No source archive, credential, or private endpoint is used.

run_id="${ECHOHOARD_ACCEPTANCE_RUN_ID:-$(date +%s)-$$}"
project="echohoard-eh105-${run_id}"
runtime_image="${ECHOHOARD_ACCEPTANCE_IMAGE:-echohoard:eh-10-05-acceptance}"
test_image="${ECHOHOARD_ACCEPTANCE_TEST_IMAGE:-echohoard:eh-10-05-tests}"
network="${project}_default"
database_url="postgresql://echohoard_test:echohoard_test@postgres:5432/echohoard_functional?schema=public"
host_port="${ECHOHOARD_ACCEPTANCE_HTTP_PORT:-33105}"
worker_key_file="$(pwd)/container/secrets/worker-key.example"
report_dir="${ECHOHOARD_ACCEPTANCE_REPORT_DIR:-.tmp/eh-10-05}"
report_file="${report_dir}/acceptance.json"

compose=(docker compose -f docker-compose.functional.yml -p "$project")
web_container="${project}-web"
worker_container="${project}-worker"
work_volume="${project}-work"
data_volume="${project}-data"

blocked() {
  echo "BLOCKED_ENV: $*" >&2
  exit 2
}

cleanup() {
  # All names are run-scoped and generated by this invocation. Compose is
  # deliberately scoped to the same unique project before removing volumes.
  docker rm --force "$web_container" "$worker_container" >/dev/null 2>&1 || true
  docker volume rm "$work_volume" "$data_volume" >/dev/null 2>&1 || true
  "${compose[@]}" down --volumes --remove-orphans >/dev/null 2>&1 || true
}
trap cleanup EXIT INT TERM

command -v docker >/dev/null 2>&1 || blocked "Docker CLI is required"
docker info >/dev/null 2>&1 || blocked "Docker daemon is unavailable"
"${compose[@]}" config --quiet

mkdir -p "$report_dir"
rm -f "$report_file"
echo "Building packaged runtime and isolated acceptance-test images"
docker build --tag "$runtime_image" .
docker build --target build --tag "$test_image" .

run_iteration() {
  local iteration="$1"
  echo "Acceptance iteration ${iteration}/2: clean PostgreSQL state"
  "${compose[@]}" down --volumes --remove-orphans >/dev/null 2>&1 || true
  # Web/worker roles are launched outside Compose. Remove the prior iteration
  # before reusing their deterministic names, ports, and disposable volumes.
  docker rm --force "$web_container" "$worker_container" >/dev/null 2>&1 || true
  docker volume rm "$work_volume" "$data_volume" >/dev/null 2>&1 || true
  "${compose[@]}" up --detach --wait postgres

  # The test image is the Dockerfile build stage, not the production runtime;
  # this keeps Prisma CLI/Vitest out of the redistributed artifact while still
  # running the complete synthetic functional suite in an isolated container.
  docker run --rm --name "${project}-tests-${iteration}" \
    --network "$network" \
    --env DATABASE_URL="$database_url" \
    "$test_image" sh -lc \
    'pnpm exec prisma migrate deploy && pnpm exec prisma generate && pnpm exec vitest run tests/functional'

  echo "Starting packaged web role and checking liveness/readiness"
  docker volume create "$work_volume" >/dev/null
  docker volume create "$data_volume" >/dev/null
  docker run --rm --user 0:0 --mount "type=volume,source=$work_volume,destination=/work" \
    --mount "type=volume,source=$data_volume,destination=/data" \
    --entrypoint /bin/sh "$runtime_image" -c \
    'chown 10002:10002 /work /data'
  docker run --detach --name "$web_container" \
    --network "$network" --publish "127.0.0.1:${host_port}:3000" \
    --env DATABASE_URL="$database_url" --env ECHOHOARD_ROLE=web "$runtime_image" >/dev/null
  wait_for_http "http://127.0.0.1:${host_port}/health" "ok"
  wait_for_http "http://127.0.0.1:${host_port}/ready" "ready"

  echo "Starting packaged worker, killing it, and checking restart convergence"
  docker run --detach --name "$worker_container" --user 10002:10002 \
    --network "$network" --env DATABASE_URL="$database_url" \
    --env ECHOHOARD_ROLE=worker --env ECHOHOARD_WORKER_STATUS_FILE=/work/worker.status \
    --mount "type=volume,source=$work_volume,destination=/work" \
    --mount "type=volume,source=$data_volume,destination=/data" \
    --mount "type=bind,source=$worker_key_file,destination=/run/echohoard/secrets/worker.key,readonly" \
    "$runtime_image" >/dev/null
  wait_for_worker_status ready
  docker kill --signal KILL "$worker_container" >/dev/null
  wait_for_container_exit "$worker_container"
  docker start "$worker_container" >/dev/null
  wait_for_worker_status ready

  echo "Iteration ${iteration}/2 passed"
}

wait_for_http() {
  local url="$1" expected="$2"
  for _attempt in $(seq 1 40); do
    if node -e '
      const [url, expected] = process.argv.slice(1);
      fetch(url).then(async (r) => {
        const body = await r.text();
        process.exit(r.ok && body.includes(expected) ? 0 : 1);
      }).catch(() => process.exit(1));
    ' "$url" "$expected"; then
      return
    fi
    sleep 1
  done
  echo "HTTP acceptance probe failed: ${url} did not contain expected status" >&2
  docker logs "$web_container" >&2 || true
  return 1
}

wait_for_worker_status() {
  local expected="$1"
  for _attempt in $(seq 1 40); do
    if [ "$(docker exec "$worker_container" sh -c 'cat /work/worker.status 2>/dev/null' || true)" = "$expected" ]; then
      return
    fi
    sleep 1
  done
  echo "Worker acceptance probe failed: status did not converge to ${expected}" >&2
  docker logs "$worker_container" >&2 || true
  return 1
}

wait_for_container_exit() {
  local container="$1"
  for _attempt in $(seq 1 20); do
    [ "$(docker inspect --format '{{.State.Status}}' "$container")" = exited ] && return
    sleep 1
  done
  echo "Worker acceptance probe failed: killed container did not exit" >&2
  return 1
}

run_iteration 1
run_iteration 2

cat > "$report_file" <<EOF
{
  "story": "EH-10-05",
  "result": "passed",
  "iterations": 2,
  "database": "synthetic-postgresql-16",
  "runtimeImage": "${runtime_image}",
  "testImage": "${test_image}",
  "checks": [
    "fresh migrations and PostgreSQL functional suite",
    "packaged web liveness and readiness",
    "packaged worker SIGKILL and restart status convergence",
    "synthetic import/media/search/conversation/health/statistics",
    "seven in-process MCP tools and duplicate convergence"
  ],
  "privateData": "not used"
}
EOF
echo "Container acceptance passed twice; sanitized evidence: ${report_file}"
